//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scratch.kodex {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://kodexengine.client/", ConfigurationName="kodex.apiSoap")]
    public interface apiSoap {
        
        // CODEGEN: Generating message contract since element name app from namespace http://kodexengine.client/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://kodexengine.client/launch", ReplyAction="*")]
        Scratch.kodex.launchResponse launch(Scratch.kodex.launchRequest request);
        
        // CODEGEN: Generating message contract since element name app from namespace http://kodexengine.client/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://kodexengine.client/isbusy", ReplyAction="*")]
        Scratch.kodex.isbusyResponse isbusy(Scratch.kodex.isbusyRequest request);
        
        // CODEGEN: Generating message contract since element name app from namespace http://kodexengine.client/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://kodexengine.client/results", ReplyAction="*")]
        Scratch.kodex.resultsResponse results(Scratch.kodex.resultsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class launchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="launch", Namespace="http://kodexengine.client/", Order=0)]
        public Scratch.kodex.launchRequestBody Body;
        
        public launchRequest() {
        }
        
        public launchRequest(Scratch.kodex.launchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://kodexengine.client/")]
    public partial class launchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string app;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string caseref;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string args;
        
        public launchRequestBody() {
        }
        
        public launchRequestBody(string app, string user, string caseref, string args) {
            this.app = app;
            this.user = user;
            this.caseref = caseref;
            this.args = args;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class launchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="launchResponse", Namespace="http://kodexengine.client/", Order=0)]
        public Scratch.kodex.launchResponseBody Body;
        
        public launchResponse() {
        }
        
        public launchResponse(Scratch.kodex.launchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://kodexengine.client/")]
    public partial class launchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool launchResult;
        
        public launchResponseBody() {
        }
        
        public launchResponseBody(bool launchResult) {
            this.launchResult = launchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isbusyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isbusy", Namespace="http://kodexengine.client/", Order=0)]
        public Scratch.kodex.isbusyRequestBody Body;
        
        public isbusyRequest() {
        }
        
        public isbusyRequest(Scratch.kodex.isbusyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://kodexengine.client/")]
    public partial class isbusyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string app;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string user;
        
        public isbusyRequestBody() {
        }
        
        public isbusyRequestBody(string app, string user) {
            this.app = app;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isbusyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isbusyResponse", Namespace="http://kodexengine.client/", Order=0)]
        public Scratch.kodex.isbusyResponseBody Body;
        
        public isbusyResponse() {
        }
        
        public isbusyResponse(Scratch.kodex.isbusyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://kodexengine.client/")]
    public partial class isbusyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool isbusyResult;
        
        public isbusyResponseBody() {
        }
        
        public isbusyResponseBody(bool isbusyResult) {
            this.isbusyResult = isbusyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class resultsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="results", Namespace="http://kodexengine.client/", Order=0)]
        public Scratch.kodex.resultsRequestBody Body;
        
        public resultsRequest() {
        }
        
        public resultsRequest(Scratch.kodex.resultsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://kodexengine.client/")]
    public partial class resultsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string app;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string user;
        
        public resultsRequestBody() {
        }
        
        public resultsRequestBody(string app, string user) {
            this.app = app;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class resultsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="resultsResponse", Namespace="http://kodexengine.client/", Order=0)]
        public Scratch.kodex.resultsResponseBody Body;
        
        public resultsResponse() {
        }
        
        public resultsResponse(Scratch.kodex.resultsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://kodexengine.client/")]
    public partial class resultsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string resultsResult;
        
        public resultsResponseBody() {
        }
        
        public resultsResponseBody(string resultsResult) {
            this.resultsResult = resultsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface apiSoapChannel : Scratch.kodex.apiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class apiSoapClient : System.ServiceModel.ClientBase<Scratch.kodex.apiSoap>, Scratch.kodex.apiSoap {
        
        public apiSoapClient() {
        }
        
        public apiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public apiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public apiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public apiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Scratch.kodex.launchResponse Scratch.kodex.apiSoap.launch(Scratch.kodex.launchRequest request) {
            return base.Channel.launch(request);
        }
        
        public bool launch(string app, string user, string caseref, string args) {
            Scratch.kodex.launchRequest inValue = new Scratch.kodex.launchRequest();
            inValue.Body = new Scratch.kodex.launchRequestBody();
            inValue.Body.app = app;
            inValue.Body.user = user;
            inValue.Body.caseref = caseref;
            inValue.Body.args = args;
            Scratch.kodex.launchResponse retVal = ((Scratch.kodex.apiSoap)(this)).launch(inValue);
            return retVal.Body.launchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Scratch.kodex.isbusyResponse Scratch.kodex.apiSoap.isbusy(Scratch.kodex.isbusyRequest request) {
            return base.Channel.isbusy(request);
        }
        
        public bool isbusy(string app, string user) {
            Scratch.kodex.isbusyRequest inValue = new Scratch.kodex.isbusyRequest();
            inValue.Body = new Scratch.kodex.isbusyRequestBody();
            inValue.Body.app = app;
            inValue.Body.user = user;
            Scratch.kodex.isbusyResponse retVal = ((Scratch.kodex.apiSoap)(this)).isbusy(inValue);
            return retVal.Body.isbusyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Scratch.kodex.resultsResponse Scratch.kodex.apiSoap.results(Scratch.kodex.resultsRequest request) {
            return base.Channel.results(request);
        }
        
        public string results(string app, string user) {
            Scratch.kodex.resultsRequest inValue = new Scratch.kodex.resultsRequest();
            inValue.Body = new Scratch.kodex.resultsRequestBody();
            inValue.Body.app = app;
            inValue.Body.user = user;
            Scratch.kodex.resultsResponse retVal = ((Scratch.kodex.apiSoap)(this)).results(inValue);
            return retVal.Body.resultsResult;
        }
    }
}
